import type {
  CarpetaNormativa,
  CondicionDecreto,
  DocumentoRequerido,
  EtapaAcreditacion,
} from '@/lib/tipos'

export const condicionesDecretoSemilla: CondicionDecreto[] = [
  {
    id: 'ci-1',
    tipo: 'Institucional',
    numero: 1,
    nombre: 'Mecanismos de selección y evaluación de estudiantes y profesores',
    descripcion: 'Reglamentos, políticas de bienestar, permanencia y graduación.',
  },
  {
    id: 'ci-2',
    tipo: 'Institucional',
    numero: 2,
    nombre: 'Estructura administrativa y académica',
    descripcion: 'Gobierno institucional, políticas y gestión de la información.',
  },
  {
    id: 'ci-3',
    tipo: 'Institucional',
    numero: 3,
    nombre: 'Cultura de la autoevaluación',
    descripcion: 'SIAC, informes periódicos y participación de la comunidad académica.',
  },
  {
    id: 'ci-4',
    tipo: 'Institucional',
    numero: 4,
    nombre: 'Programa de egresados',
    descripcion: 'Políticas y seguimiento a egresados.',
  },
  {
    id: 'ci-5',
    tipo: 'Institucional',
    numero: 5,
    nombre: 'Modelo de bienestar',
    descripcion: 'Programas de bienestar y prevención de deserción.',
  },
  {
    id: 'ci-6',
    tipo: 'Institucional',
    numero: 6,
    nombre: 'Recursos suficientes',
    descripcion: 'Talento humano, infraestructura y recursos financieros.',
  },
  {
    id: 'cp-1',
    tipo: 'Programa',
    numero: 1,
    nombre: 'Denominación',
    descripcion: 'Nombre del programa coherente con título y contenido curricular.',
  },
  {
    id: 'cp-2',
    tipo: 'Programa',
    numero: 2,
    nombre: 'Justificación',
    descripcion: 'Estudio de pertinencia y necesidades del país.',
  },
  {
    id: 'cp-3',
    tipo: 'Programa',
    numero: 3,
    nombre: 'Aspectos curriculares',
    descripcion: 'Plan de estudios, resultados de aprendizaje y evaluación.',
  },
  {
    id: 'cp-4',
    tipo: 'Programa',
    numero: 4,
    nombre: 'Organización de actividades académicas',
    descripcion: 'Distribución de horas y créditos académicos.',
  },
  {
    id: 'cp-5',
    tipo: 'Programa',
    numero: 5,
    nombre: 'Investigación, innovación y creación',
    descripcion: 'Estrategias de formación investigativa del programa.',
  },
  {
    id: 'cp-6',
    tipo: 'Programa',
    numero: 6,
    nombre: 'Relación con el sector externo',
    descripcion: 'Vinculación con sectores productivo, social y cultural.',
  },
  {
    id: 'cp-7',
    tipo: 'Programa',
    numero: 7,
    nombre: 'Profesores',
    descripcion: 'Planta docente, formación y experiencia.',
  },
  {
    id: 'cp-8',
    tipo: 'Programa',
    numero: 8,
    nombre: 'Medios educativos',
    descripcion: 'Ambientes virtuales, bibliografía y equipos.',
  },
  {
    id: 'cp-9',
    tipo: 'Programa',
    numero: 9,
    nombre: 'Infraestructura física y tecnológica',
    descripcion: 'Ambientes de aprendizaje y convenios de infraestructura.',
  },
]

export const etapasAcreditacionSemilla: EtapaAcreditacion[] = [
  {
    id: 'etapa-pre',
    nombre: 'Pre-radicación (Condiciones institucionales)',
    tipo: 'PreRadicacion',
    descripcion: 'Verificación de las 6 condiciones institucionales ante CONACES.',
    orden: 1,
    activa: true,
  },
  {
    id: 'etapa-rad',
    nombre: 'Radicación (Condiciones de programa)',
    tipo: 'Radicacion',
    descripcion: 'Evaluación de las 9 condiciones de calidad del programa académico.',
    orden: 2,
    activa: true,
  },
  {
    id: 'etapa-auto',
    nombre: 'Autoevaluación institucional',
    tipo: 'Autoevaluacion',
    descripcion: 'Ciclo de autoevaluación, informes y plan de mejoramiento.',
    orden: 3,
    activa: true,
  },
  {
    id: 'etapa-ren',
    nombre: 'Renovación de registro calificado',
    tipo: 'Renovacion',
    descripcion: 'Documentación adicional para renovación cada 7 años.',
    orden: 4,
    activa: true,
  },
]

export const carpetasNormativasSemilla: CarpetaNormativa[] = [
  {
    id: 'carp-ci-1',
    etapaId: 'etapa-pre',
    condicionId: 'ci-1',
    nombre: 'CI 1 · Selección y evaluación',
    descripcion: 'Reglamento estudiantil y reglamento profesoral.',
    orden: 1,
    activa: true,
  },
  {
    id: 'carp-ci-2',
    etapaId: 'etapa-pre',
    condicionId: 'ci-2',
    nombre: 'CI 2 · Estructura administrativa',
    descripcion: 'Gobierno, políticas y arquitectura institucional.',
    orden: 2,
    activa: true,
  },
  {
    id: 'carp-ci-3',
    etapaId: 'etapa-pre',
    condicionId: 'ci-3',
    nombre: 'CI 3 · Autoevaluación',
    descripcion: 'Informe de autoevaluación de condiciones institucionales.',
    orden: 3,
    activa: true,
  },
  {
    id: 'carp-ci-4',
    etapaId: 'etapa-pre',
    condicionId: 'ci-4',
    nombre: 'CI 4 · Egresados',
    descripcion: 'Programa de seguimiento a egresados.',
    orden: 4,
    activa: true,
  },
  {
    id: 'carp-ci-5',
    etapaId: 'etapa-pre',
    condicionId: 'ci-5',
    nombre: 'CI 5 · Bienestar',
    descripcion: 'Modelo de bienestar institucional.',
    orden: 5,
    activa: true,
  },
  {
    id: 'carp-ci-6',
    etapaId: 'etapa-pre',
    condicionId: 'ci-6',
    nombre: 'CI 6 · Recursos',
    descripcion: 'Evidencias de talento humano e infraestructura.',
    orden: 6,
    activa: true,
  },
  {
    id: 'carp-cp-1',
    etapaId: 'etapa-rad',
    condicionId: 'cp-1',
    nombre: 'CP 1 · Denominación',
    descripcion: 'Denominación y coherencia del título.',
    orden: 1,
    activa: true,
  },
  {
    id: 'carp-cp-2',
    etapaId: 'etapa-rad',
    condicionId: 'cp-2',
    nombre: 'CP 2 · Justificación',
    descripcion: 'Estudio de pertinencia del programa.',
    orden: 2,
    activa: true,
  },
  {
    id: 'carp-cp-3',
    etapaId: 'etapa-rad',
    condicionId: 'cp-3',
    nombre: 'CP 3 · Currículo',
    descripcion: 'Documento maestro y plan de estudios.',
    orden: 3,
    activa: true,
  },
  {
    id: 'carp-auto-1',
    etapaId: 'etapa-auto',
    condicionId: 'ci-3',
    nombre: 'Autoevaluación · Informes',
    descripcion: 'Informes y matrices de autoevaluación institucional.',
    orden: 1,
    activa: true,
  },
  {
    id: 'carp-auto-2',
    etapaId: 'etapa-auto',
    nombre: 'Plan de mejoramiento',
    descripcion: 'Seguimiento al plan derivado de la autoevaluación.',
    orden: 2,
    activa: true,
  },
  {
    id: 'carp-ren-1',
    etapaId: 'etapa-ren',
    nombre: 'Renovación · Documentación',
    descripcion: 'Documentos para renovación del registro calificado.',
    orden: 1,
    activa: true,
  },
]

export const documentosRequeridosSemilla: DocumentoRequerido[] = [
  {
    id: 'doc-001',
    carpetaId: 'carp-ci-1',
    nombre: 'Reglamento estudiantil',
    esPlantilla: true,
    formato: 'DOCX',
    obligatorio: true,
    orden: 1,
  },
  {
    id: 'doc-002',
    carpetaId: 'carp-ci-1',
    nombre: 'Reglamento profesoral',
    esPlantilla: true,
    formato: 'DOCX',
    obligatorio: true,
    orden: 2,
  },
  {
    id: 'doc-003',
    carpetaId: 'carp-ci-3',
    nombre: 'Informe de autoevaluación institucional',
    esPlantilla: true,
    formato: 'DOCX',
    obligatorio: true,
    orden: 1,
  },
  {
    id: 'doc-004',
    carpetaId: 'carp-cp-2',
    nombre: 'Estudio de pertinencia',
    esPlantilla: true,
    formato: 'DOCX',
    obligatorio: true,
    orden: 1,
  },
  {
    id: 'doc-005',
    carpetaId: 'carp-cp-3',
    nombre: 'Documento maestro de programa',
    esPlantilla: true,
    formato: 'DOCX',
    obligatorio: true,
    orden: 1,
  },
  {
    id: 'doc-006',
    carpetaId: 'carp-cp-3',
    nombre: 'Acto administrativo de creación',
    esPlantilla: false,
    formato: 'PDF',
    obligatorio: true,
    orden: 2,
  },
  {
    id: 'doc-007',
    carpetaId: 'carp-auto-1',
    nombre: 'Informe de autoevaluación institucional',
    esPlantilla: true,
    formato: 'DOCX',
    obligatorio: true,
    orden: 1,
  },
  {
    id: 'doc-008',
    carpetaId: 'carp-auto-2',
    nombre: 'Plan de mejoramiento',
    esPlantilla: true,
    formato: 'DOCX',
    obligatorio: true,
    orden: 1,
  },
  {
    id: 'doc-009',
    carpetaId: 'carp-ren-1',
    nombre: 'Solicitud de renovación de registro calificado',
    esPlantilla: false,
    formato: 'PDF',
    obligatorio: true,
    orden: 1,
  },
  {
    id: 'doc-010',
    carpetaId: 'carp-ren-1',
    nombre: 'Informe de seguimiento al registro calificado',
    esPlantilla: true,
    formato: 'DOCX',
    obligatorio: true,
    orden: 2,
  },
]
