import type { Evidencia } from '@/lib/tipos'

export const evidenciasSemilla: Evidencia[] = [
  {
    id: 'ev-001',
    nombre: 'Informe de autoevaluación institucional',
    programaId: 'prog-isw',
    periodo: '2024-2',
    factor: 'Factor 1',
    indicador: 'Autoevaluación CI',
    estado: 'EnRevision',
    autorId: 'usr-cargador',
    nombreArchivo: 'informe-autoevaluacion-institucional.pdf',
    fechaCarga: '2024-08-28',
    responsable: 'Laura R.',
    documentoRequeridoId: 'doc-003',
  },
  {
    id: 'ev-002',
    nombre: 'Actas de comité curricular',
    programaId: 'prog-der',
    periodo: '2025-1',
    factor: 'Factor 4',
    indicador: 'Pertinencia curricular',
    estado: 'Validado',
    autorId: 'usr-cargador',
    nombreArchivo: 'actas-comite-curricular.pdf',
    fechaCarga: '2024-08-25',
    responsable: 'María C.',
  },
  {
    id: 'ev-003',
    nombre: 'Plan de mejoramiento 2026',
    programaId: 'prog-med',
    periodo: '2026-1',
    factor: 'Factor 10',
    indicador: 'Seguimiento al plan',
    estado: 'Borrador',
    autorId: 'usr-cargador',
    nombreArchivo: 'plan-mejoramiento-2026.xlsx',
    fechaCarga: '2024-08-22',
    responsable: 'Carlos M.',
  },
  {
    id: 'ev-004',
    nombre: 'Resultados pruebas Saber Pro',
    programaId: 'prog-isw',
    periodo: '2025-2',
    factor: 'Factor 5',
    indicador: 'Desempeño estudiantil',
    estado: 'Validado',
    autorId: 'usr-cargador',
    nombreArchivo: 'resultados-saber-pro.pdf',
    fechaCarga: '2024-08-18',
    responsable: 'Laura R.',
  },
  {
    id: 'ev-005',
    nombre: 'Seguimiento a egresados',
    programaId: 'prog-ade',
    periodo: '2024-2',
    factor: 'Factor 7',
    indicador: 'Inserción laboral',
    estado: 'Rechazado',
    autorId: 'usr-cargador',
    nombreArchivo: 'seguimiento-egresados.xlsx',
    fechaCarga: '2024-08-10',
    observaciones: 'Falta la fuente de datos y la periodicidad del indicador.',
    responsable: 'Ana P.',
  },
  {
    id: 'ev-006',
    nombre: 'Matriz de evidencias',
    programaId: 'prog-enf',
    periodo: '2024-2',
    factor: 'Factor 1',
    indicador: 'Gestión documental',
    estado: 'EnRevision',
    autorId: 'usr-cargador',
    nombreArchivo: 'matriz-evidencias.xlsx',
    fechaCarga: '2024-08-15',
    responsable: 'Pedro G.',
  },
  {
    id: 'ev-007',
    nombre: 'Estudio de pertinencia',
    programaId: 'prog-cib',
    periodo: '2025-1',
    factor: 'Factor 2',
    indicador: 'Justificación',
    estado: 'Borrador',
    autorId: 'usr-cargador',
    nombreArchivo: 'estudio-pertinencia.docx',
    fechaCarga: '2024-08-20',
    responsable: 'Diego F.',
    documentoRequeridoId: 'doc-004',
  },
  {
    id: 'ev-008',
    nombre: 'Documento maestro de programa',
    programaId: 'prog-inv',
    periodo: '2025-1',
    factor: 'Factor 3',
    indicador: 'Currículo',
    estado: 'EnRevision',
    autorId: 'usr-cargador',
    nombreArchivo: 'documento-maestro.docx',
    fechaCarga: '2024-08-12',
    responsable: 'Sandra L.',
    documentoRequeridoId: 'doc-005',
  },
  {
    id: 'ev-009',
    nombre: 'Reglamento estudiantil',
    programaId: 'prog-der',
    periodo: '2024-1',
    factor: 'Institucional',
    indicador: 'CI 1',
    estado: 'Validado',
    autorId: 'usr-cargador',
    nombreArchivo: 'reglamento-estudiantil.pdf',
    fechaCarga: '2024-07-30',
    responsable: 'Laura R.',
    documentoRequeridoId: 'doc-001',
  },
  {
    id: 'ev-010',
    nombre: 'Planta docente consolidada',
    programaId: 'prog-psi',
    periodo: '2025-2',
    factor: 'Factor 5',
    indicador: 'Profesores',
    estado: 'Borrador',
    autorId: 'usr-cargador',
    nombreArchivo: 'planta-docente.xlsx',
    fechaCarga: '2024-08-26',
    responsable: 'Jorge H.',
  },
  {
    id: 'ev-011',
    nombre: 'Informe de proyección social',
    programaId: 'prog-com',
    periodo: '2024-2',
    factor: 'Factor 6',
    indicador: 'Relación entorno',
    estado: 'Rechazado',
    autorId: 'usr-cargador',
    nombreArchivo: 'proyeccion-social.pdf',
    fechaCarga: '2024-08-05',
    observaciones: 'Completar datos de convenios vigentes.',
    responsable: 'Marta V.',
  },
  {
    id: 'ev-012',
    nombre: 'Permiso de uso de suelo',
    programaId: 'prog-arc',
    periodo: '2024-2',
    factor: 'Institucional',
    indicador: 'CI 6',
    estado: 'Validado',
    autorId: 'usr-cargador',
    nombreArchivo: 'permiso-uso-suelo.pdf',
    fechaCarga: '2024-06-15',
    responsable: 'Oscar A.',
  },
  {
    id: 'ev-013',
    nombre: 'Informe de autoevaluación programa',
    programaId: 'prog-der',
    periodo: '2023-1',
    factor: 'Factor 1',
    indicador: 'Autoevaluación CP',
    estado: 'Validado',
    autorId: 'usr-cargador',
    nombreArchivo: 'informe-autoevaluacion-der.pdf',
    fechaCarga: '2023-11-20',
    responsable: 'Laura R.',
  },
  {
    id: 'ev-014',
    nombre: 'Convenio docencia-servicio',
    programaId: 'prog-enf',
    periodo: '2025-1',
    factor: 'Factor 8',
    indicador: 'Infraestructura',
    estado: 'EnRevision',
    autorId: 'usr-cargador',
    nombreArchivo: 'convenio-docencia-servicio.pdf',
    fechaCarga: '2024-08-01',
    responsable: 'Claudia R.',
  },
  {
    id: 'ev-015',
    nombre: 'Política de investigación',
    programaId: 'prog-isw',
    periodo: '2024-2',
    factor: 'Institucional',
    indicador: 'CI 2',
    estado: 'Validado',
    autorId: 'usr-cargador',
    nombreArchivo: 'politica-investigacion.pdf',
    fechaCarga: '2024-05-10',
    responsable: 'Laura R.',
  },
  {
    id: 'ev-016',
    nombre: 'Reglamento profesoral',
    programaId: 'prog-der',
    periodo: '2024-1',
    factor: 'Institucional',
    indicador: 'CI 1',
    estado: 'Validado',
    autorId: 'usr-cargador',
    nombreArchivo: 'reglamento-profesoral.pdf',
    fechaCarga: '2024-07-28',
    responsable: 'María C.',
    documentoRequeridoId: 'doc-002',
  },
  {
    id: 'ev-017',
    nombre: 'Acto administrativo de creación',
    programaId: 'prog-inv',
    periodo: '2025-1',
    factor: 'Programa',
    indicador: 'CP 3',
    estado: 'Validado',
    autorId: 'usr-cargador',
    nombreArchivo: 'acto-administrativo-creacion.pdf',
    fechaCarga: '2024-07-15',
    responsable: 'Sandra L.',
    documentoRequeridoId: 'doc-006',
  },
  {
    id: 'ev-018',
    nombre: 'Plan de mejoramiento',
    programaId: 'prog-med',
    periodo: '2026-1',
    factor: 'Autoevaluación',
    indicador: 'Seguimiento',
    estado: 'Borrador',
    autorId: 'usr-cargador',
    nombreArchivo: 'plan-mejoramiento-auto.docx',
    fechaCarga: '2024-08-01',
    responsable: 'Carlos M.',
    documentoRequeridoId: 'doc-008',
  },
  {
    id: 'ev-019',
    nombre: 'Solicitud de renovación de registro calificado',
    programaId: 'prog-isw',
    periodo: '2024-2',
    factor: 'Renovación',
    indicador: 'Registro calificado',
    estado: 'Borrador',
    autorId: 'usr-cargador',
    nombreArchivo: 'solicitud-renovacion.pdf',
    fechaCarga: '2024-06-01',
    responsable: 'Laura R.',
    documentoRequeridoId: 'doc-009',
  },
]
