import { URL_DOCUMENTO_DEMO_SIAC } from '@/lib/constantes/documentos'
import type { Plantilla } from '@/lib/tipos'

export const plantillasSemilla: Plantilla[] = [
  {
    id: 'plt-001',
    nombre: 'Informe de autoevaluación',
    factor: 'Autoevaluación · CI / CP',
    formato: 'DOCX',
    version: 'v3.2',
    vigente: true,
    categoria: 'Autoevaluacion',
    descripcion: 'Formato oficial para informes de autoevaluación institucional y de programa.',
    urlDocumento: URL_DOCUMENTO_DEMO_SIAC,
  },
  {
    id: 'plt-002',
    nombre: 'Matriz de evidencias',
    factor: 'Gestión documental',
    formato: 'XLSX',
    version: 'v2.1',
    vigente: true,
    categoria: 'Institucional',
    descripcion: 'Matriz para organizar evidencias por condición e indicador.',
  },
  {
    id: 'plt-003',
    nombre: 'Plan de mejoramiento',
    factor: 'Seguimiento · CI / CP',
    formato: 'DOCX',
    version: 'v1.8',
    vigente: true,
    categoria: 'Autoevaluacion',
    descripcion: 'Plantilla del plan de mejoramiento derivado del informe de autoevaluación.',
  },
  {
    id: 'plt-004',
    nombre: 'Estudio de pertinencia',
    factor: 'CP 2 · Justificación',
    formato: 'DOCX',
    version: 'v2.0',
    vigente: true,
    categoria: 'Programa',
    descripcion: 'Formato para estudio de pertinencia de programas nuevos.',
  },
  {
    id: 'plt-005',
    nombre: 'Documento maestro de programa',
    factor: 'CP 3 · Currículo',
    formato: 'DOCX',
    version: 'v4.1',
    vigente: true,
    categoria: 'Programa',
    descripcion: 'Documento maestro con las 9 condiciones de programa.',
  },
  {
    id: 'plt-006',
    nombre: 'Reglamento estudiantil',
    factor: 'CI 1 · Selección',
    formato: 'DOCX',
    version: 'v1.5',
    vigente: true,
    categoria: 'Institucional',
    descripcion: 'Plantilla base del reglamento estudiantil institucional.',
  },
  {
    id: 'plt-007',
    nombre: 'Reglamento profesoral',
    factor: 'CI 1 · Selección',
    formato: 'DOCX',
    version: 'v1.3',
    vigente: true,
    categoria: 'Institucional',
    descripcion: 'Plantilla base del reglamento profesoral.',
  },
  {
    id: 'plt-008',
    nombre: 'Informe de autoevaluación',
    factor: 'Autoevaluación · CI / CP',
    formato: 'DOCX',
    version: 'v3.1',
    vigente: false,
    categoria: 'Autoevaluacion',
    descripcion: 'Versión anterior del informe de autoevaluación.',
  },
  {
    id: 'plt-009',
    nombre: 'Formato planta docente',
    factor: 'CP 7 · Profesores',
    formato: 'XLSX',
    version: 'v1.0',
    vigente: true,
    categoria: 'Programa',
    descripcion: 'Consolidado de hojas de vida y dedicación docente.',
  },
  {
    id: 'plt-010',
    nombre: 'Modelo de bienestar',
    factor: 'CI 5 · Bienestar',
    formato: 'PDF',
    version: 'v2.2',
    vigente: true,
    categoria: 'Institucional',
    descripcion: 'Documento guía del modelo de bienestar institucional.',
    urlDocumento: URL_DOCUMENTO_DEMO_SIAC,
  },
  {
    id: 'plt-ci-docsiac',
    nombre: 'Documentación del proyecto SIAC',
    factor: 'CI · Documentación institucional',
    formato: 'PDF',
    version: 'v1.0',
    vigente: true,
    categoria: 'Institucional',
    descripcion:
      'Documento de referencia del SIAC para práctica del visualizador. Archivo: SIAC_Documentacion_Proyecto.pdf',
    urlDocumento: URL_DOCUMENTO_DEMO_SIAC,
  },
]
