import type { Programa } from '@/lib/tipos'

export const programasSemilla: Programa[] = [
  {
    id: 'prog-der',
    nombre: 'Derecho',
    codigo: 'DER-01',
    nivel: 'Pregrado',
    semaforo: 'Verde',
    porcentajeAvance: 85,
    estadoProceso: 'En autoevaluación',
  },
  {
    id: 'prog-isw',
    nombre: 'Ingeniería de Software',
    codigo: 'ISW-02',
    nivel: 'Pregrado',
    semaforo: 'Amarillo',
    porcentajeAvance: 74,
    estadoProceso: 'En autoevaluación',
  },
  {
    id: 'prog-ade',
    nombre: 'Administración de Empresas',
    codigo: 'ADE-03',
    nivel: 'Pregrado',
    semaforo: 'Verde',
    porcentajeAvance: 92,
    estadoProceso: 'Documentación completa',
  },
  {
    id: 'prog-med',
    nombre: 'Maestría en Educación',
    codigo: 'MED-05',
    nivel: 'Posgrado',
    semaforo: 'Amarillo',
    porcentajeAvance: 68,
    estadoProceso: 'En revisión interna',
  },
  {
    id: 'prog-enf',
    nombre: 'Enfermería',
    codigo: 'ENF-04',
    nivel: 'Pregrado',
    semaforo: 'Verde',
    porcentajeAvance: 88,
    estadoProceso: 'En autoevaluación',
  },
  {
    id: 'prog-psi',
    nombre: 'Psicología',
    codigo: 'PSI-06',
    nivel: 'Pregrado',
    semaforo: 'Amarillo',
    porcentajeAvance: 71,
    estadoProceso: 'En autoevaluación',
  },
  {
    id: 'prog-con',
    nombre: 'Contaduría Pública',
    codigo: 'CON-07',
    nivel: 'Pregrado',
    semaforo: 'Verde',
    porcentajeAvance: 90,
    estadoProceso: 'Documentación completa',
  },
  {
    id: 'prog-com',
    nombre: 'Comunicación Social',
    codigo: 'COM-08',
    nivel: 'Pregrado',
    semaforo: 'Rojo',
    porcentajeAvance: 31,
    estadoProceso: 'Requiere atención',
  },
  {
    id: 'prog-mba',
    nombre: 'MBA',
    codigo: 'MBA-09',
    nivel: 'Posgrado',
    semaforo: 'Amarillo',
    porcentajeAvance: 65,
    estadoProceso: 'En autoevaluación',
  },
  {
    id: 'prog-inv',
    nombre: 'Innovación Educativa',
    codigo: 'INV-10',
    nivel: 'Posgrado',
    semaforo: 'Rojo',
    porcentajeAvance: 28,
    estadoProceso: 'Registro nuevo',
  },
  {
    id: 'prog-cib',
    nombre: 'Ciberseguridad',
    codigo: 'CIB-11',
    nivel: 'Posgrado',
    semaforo: 'Amarillo',
    porcentajeAvance: 55,
    estadoProceso: 'Registro nuevo',
  },
  {
    id: 'prog-arc',
    nombre: 'Arquitectura',
    codigo: 'ARC-12',
    nivel: 'Pregrado',
    semaforo: 'Verde',
    porcentajeAvance: 82,
    estadoProceso: 'En autoevaluación',
  },
]

export const factoresSemilla = [
  'Factor 1 · Proyecto educativo',
  'Factor 4 · Procesos académicos',
  'Factor 5 · Profesores',
  'Factor 7 · Egresados',
  'Factor 10 · Mejoramiento',
]

export const periodosSemilla = ['2024-1', '2024-2', '2025-1', '2025-2', '2026-1']
